[workspace]
resolver = "3"
members = [
    "server",
    "signing",
    "types",
    "worker"
]

[workspace.dependencies]
kubernix-signing = { version = "0.1.0", path = "./signing" }
kubernix-types = { version = "0.1.0", path = "./types" }

async-nats = "0.50.0"
async-trait = "0.1.92"
aws-config = "1.10.1"
aws-sdk-s3 = "1.140"
capnp = { version = "0.27", features = ["alloc", "std"] }
ed25519-dalek = { version = "3", features = ["digest", "rand_core"] }
futures-util = "0.3.33"
sha2 = "0.11"
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = { version = "0.1.19", features = ["sync"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.24.0", features = ["v4", "serde"] }
zstd = "0.13.3"
