[workspace]
resolver = "3"
members = [
    "daemon-protocol",
    "guest-agent",
    "server",
    "signing",
    "types",
    "worker"
]

[workspace.dependencies]
kubernix-daemon-protocol = { version = "0.1.0", path = "./daemon-protocol" }
kubernix-signing = { version = "0.1.0", path = "./signing" }
kubernix-types = { version = "0.1.0", path = "./types" }

async-compression = { version = "0.4", features = ["tokio", "zstd"] }
async-nats = "0.50.0"
async-trait = "0.1.92"
aws-config = "1.10.1"
aws-sdk-s3 = "1.140"
capnp = { version = "0.27", features = ["alloc", "std"] }
color-eyre = "0.6.5"
digest-io-async = { version = "0.1.0", features = ["tokio"] }
ed25519-dalek = { version = "3", features = ["digest", "rand_core"] }
eyre = "0.6.14"
futures-util = "0.3.33"
sha2 = "0.11"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["full"] }
tokio-stream = { version = "0.1.19", features = ["sync"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.24.0", features = ["v4", "serde"] }
zstd = "0.13.3"

[patch.crates-io]
# AsyncRead/AsyncWrite support
# https://github.com/RustCrypto/utils/pull/1518
digest-io-async = { git = "https://github.com/baloo/utils.git", branch = "push-kxltlypsyruw" }
