{{- if .Values.cache.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-cache" (include "kubernix.fullname" .) }}
  labels:
    {{- include "kubernix.labels" . | nindent 4 }}
  {{- with .Values.cache.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.cache.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range .Values.cache.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ printf "%s-cache" (include "kubernix.fullname" $) }}
                port:
                  name: http
          {{- end }}
    {{- end }}
  {{- with .Values.cache.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
