apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-cache" (include "kubernix.fullname" .) }}
  labels:
    {{- include "kubernix.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cache.service.type }}
  selector:
    {{- include "kubernix.selectorLabels" (dict "context" $ "component" "cache") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.cache.service.port }}
      targetPort: http
