{{- $backupS3 := include "kubernix.postgresBackupS3" . | fromJson -}}
{{- if $backupS3.createOwnSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $backupS3.secretName }}
  labels:
    {{- include "kubernix.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKeyId: {{ $backupS3.accessKeyId | quote }}
  secretAccessKey: {{ $backupS3.secretAccessKey | quote }}
{{- end }}
