{{- if not .Values.s3.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-s3" (include "kubernix.fullname" .) }}
  labels:
    {{- include "kubernix.labels" . | nindent 4 }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.s3.accessKeyId | quote }}
  secretAccessKey: {{ .Values.s3.secretAccessKey | quote }}
{{- end }}
