{{- include "kubernix.worker.scaledobject" (dict "context" $ "name" "" "worker" .Values.worker) }}
{{- range $name, $worker := .Values.workers }}
{{ include "kubernix.worker.scaledobject" (dict "context" $ "name" $name "worker" $worker) }}
{{- end }}
