//! Extension traits and conversions for the capnp-generated daemon protocol
//! types, and for a couple of foreign types `daemon_rpc` otherwise had to
//! wrap in free functions.
//!
//! Every `Reader`/`Builder`/`Client` type here is generated by capnpc into
//! this crate (see `lib.rs`'s `daemon_capnp`/`types_capnp` modules and
//! `build.rs`), so it is "local" for orphan-rule purposes even though it
//! reads like a foreign/remote type — which is exactly why attaching these as
//! methods reads naturally: `reader.to_store_path(store_dir)` rather than
//! `read_store_path(reader, store_dir)`.

use futures_util::StreamExt as _;

use crate::daemon_capnp::legacy_protocol;
use crate::jobs::JobQueue;
use crate::logging_capnp::log_stream;
use crate::rpc_error;
use crate::store::{Hash, HashType, PathInfo, StoreError};
use crate::store_path::{CaMethod, ContentAddress};
use kubernix_types::StorePath;

impl From<&StoreError> for capnp::Error {
    fn from(e: &StoreError) -> Self {
        match e {
            StoreError::Unsupported(op) => rpc_error::unimplemented(op),
            other => rpc_error::failed(other.to_string()),
        }
    }
}

impl From<StoreError> for capnp::Error {
    fn from(e: StoreError) -> Self {
        (&e).into()
    }
}

/// The one place an internal error becomes something a Nix client sees.
pub trait ReportExt {
    /// `context` is a short label for what was being attempted (e.g. `"fetching
    /// object"`) — used only in the generic fallback message, so it should read
    /// fine standing alone, without the error text that follows it elsewhere.
    ///
    /// Known-safe domain errors are shown via their own `Display`; a call site
    /// that already knows its message is safe can mark it with
    /// [`kubernix_types::errors::Public`] as the report's root cause. Anything
    /// else is logged in full and replaced with a generic message — an S3
    /// request id or a Postgres error string is not this client's business.
    fn into_capnp_error(self, context: &str) -> capnp::Error;
}

impl ReportExt for eyre::Report {
    fn into_capnp_error(self, context: &str) -> capnp::Error {
        if let Some(e) = self.downcast_ref::<StoreError>() {
            return e.into();
        }
        if let Some(e) = self.downcast_ref::<kubernix_signing::SignError>() {
            return rpc_error::failed(e.to_string());
        }
        if let Some(message) = kubernix_types::errors::public_message(&self) {
            return rpc_error::failed(message);
        }
        tracing::error!(error = ?self, %context, "internal error serving daemon protocol request");
        rpc_error::failed(format!("kubernix: {context} failed; see server logs"))
    }
}

/// A `.drv`'s own name, with the trailing `.drv` stripped — mirrors Nix's
/// `Derivation::nameFromPath`. Used to recompute a fixed output's path
/// independent of whatever the `.drv` itself claims
/// ([`crate::store_path::StoreDir::verify_fixed_output`]).
pub trait StorePathExt {
    fn derivation_name(&self) -> &str;
}

impl StorePathExt for StorePath {
    fn derivation_name(&self) -> &str {
        let name = self.name().unwrap_or_default();
        name.strip_suffix(".drv").unwrap_or(name)
    }
}

impl From<legacy_protocol::HashType> for HashType {
    fn from(ht: legacy_protocol::HashType) -> Self {
        match ht {
            legacy_protocol::HashType::Md5 => HashType::Md5,
            legacy_protocol::HashType::Sha1 => HashType::Sha1,
            legacy_protocol::HashType::Sha256 => HashType::Sha256,
            legacy_protocol::HashType::Sha512 => HashType::Sha512,
        }
    }
}

impl From<HashType> for legacy_protocol::HashType {
    fn from(ht: HashType) -> Self {
        match ht {
            HashType::Md5 => legacy_protocol::HashType::Md5,
            HashType::Sha1 => legacy_protocol::HashType::Sha1,
            HashType::Sha256 => legacy_protocol::HashType::Sha256,
            HashType::Sha512 => legacy_protocol::HashType::Sha512,
        }
    }
}

/// `StorePath.raw` carries the full printed path (`types-rpc.hh:25-38`).
pub trait StorePathReaderExt {
    /// Refused, rather than silently reinterpreted, if it is not actually
    /// rooted at `store_dir`: this connection's client and the frontend must
    /// agree on the store directory, or every path-derived computation
    /// downstream (content verification, signing) would be operating on the
    /// wrong bytes.
    fn to_store_path(&self, store_dir: &str) -> capnp::Result<StorePath>;
}

impl StorePathReaderExt for crate::types_capnp::store_path::Reader<'_> {
    fn to_store_path(&self, store_dir: &str) -> capnp::Result<StorePath> {
        let raw = String::from_utf8_lossy(self.get_raw()?).into_owned();
        StorePath::from_full(store_dir, &raw).ok_or_else(|| {
            rpc_error::failed(format!(
                "kubernix: {raw} is not rooted at this server's store directory \
                 ({store_dir}); the client and the frontend must use the same store dir"
            ))
        })
    }
}

pub trait StorePathListReaderExt {
    fn to_store_paths(&self, store_dir: &str) -> capnp::Result<Vec<StorePath>>;
}

impl StorePathListReaderExt
    for capnp::struct_list::Reader<'_, crate::types_capnp::store_path::Owned>
{
    fn to_store_paths(&self, store_dir: &str) -> capnp::Result<Vec<StorePath>> {
        self.iter().map(|r| r.to_store_path(store_dir)).collect()
    }
}

pub trait StorePathListBuilderExt {
    fn write_store_paths(&mut self, paths: &[StorePath], store_dir: &str);
}

impl StorePathListBuilderExt
    for capnp::struct_list::Builder<'_, crate::types_capnp::store_path::Owned>
{
    fn write_store_paths(&mut self, paths: &[StorePath], store_dir: &str) {
        for (i, path) in paths.iter().enumerate() {
            self.reborrow()
                .get(i as u32)
                .set_raw(path.to_full(store_dir).as_bytes());
        }
    }
}

/// Returns the store path a `DerivedPath` names, and whether it is the
/// `built` variant (i.e. names a derivation to realise rather than a path to
/// check).
pub trait DerivedPathReaderExt {
    fn resolve_target(&self, store_dir: &str) -> capnp::Result<(StorePath, bool)>;
}

impl DerivedPathReaderExt for legacy_protocol::derived_path::Reader<'_> {
    fn resolve_target(&self, store_dir: &str) -> capnp::Result<(StorePath, bool)> {
        use legacy_protocol::derived_path;
        Ok(match self.get_raw().which()? {
            derived_path::raw::Which::Opaque(opaque) => {
                (opaque?.get_path()?.to_store_path(store_dir)?, false)
            }
            derived_path::raw::Which::Built(built) => (
                built?.get_drv_path()?.get_path()?.to_store_path(store_dir)?,
                true,
            ),
        })
    }
}

/// Read/write a `ValidPathInfo` off/onto the wire.
pub trait ValidPathInfoReaderExt {
    fn to_path_info(&self, store_dir: &str) -> capnp::Result<PathInfo>;
}

impl ValidPathInfoReaderExt for legacy_protocol::valid_path_info::Reader<'_> {
    fn to_path_info(&self, store_dir: &str) -> capnp::Result<PathInfo> {
        use crate::types_capnp::option;

        let path = self.get_path()?.to_store_path(store_dir)?;
        let unkeyed = self.get_unkeyed_valid_path_info()?;

        let deriver = match unkeyed.get_deriver()?.which()? {
            option::Which::None(()) => None,
            option::Which::Some(sp) => Some(sp?.to_store_path(store_dir)?),
        };

        let nar_hash_reader = unkeyed.get_nar_hash()?;
        let nar_hash = Hash {
            hash_type: nar_hash_reader.get_hash_type()?.into(),
            bytes: nar_hash_reader.get_hash()?.to_vec(),
        };

        let sigs = unkeyed
            .get_sigs()?
            .iter()
            .map(|s| Ok(String::from_utf8_lossy(s?).into_owned()))
            .collect::<capnp::Result<Vec<_>>>()?;

        Ok(PathInfo {
            path,
            deriver,
            nar_hash,
            nar_size: unkeyed.get_nar_size(),
            references: unkeyed.get_references()?.to_store_paths(store_dir)?,
            registration_time: unkeyed.get_registration_time(),
            ultimate: unkeyed.get_ultimate(),
            sigs,
        })
    }
}

/// The content address a client attached to a path, if any.
///
/// Its absence is the interesting case: a path with no content address is
/// input-addressed, so nothing about its name follows from its bytes and the
/// frontend has no way to check the client's claim. See [`crate::store::Tier`].
pub trait UnkeyedValidPathInfoReaderExt {
    fn to_content_address(&self) -> capnp::Result<Option<ContentAddress>>;
}

impl UnkeyedValidPathInfoReaderExt for legacy_protocol::unkeyed_valid_path_info::Reader<'_> {
    fn to_content_address(&self) -> capnp::Result<Option<ContentAddress>> {
        use crate::types_capnp::option;

        let ca = match self.get_ca()?.which()? {
            option::Which::None(()) => return Ok(None),
            option::Which::Some(ca) => ca?,
        };

        let method = match ca.get_method()? {
            legacy_protocol::ContentAddressMethod::TextIngestion => CaMethod::Text,
            legacy_protocol::ContentAddressMethod::FlatFileIngestion => CaMethod::Flat,
            legacy_protocol::ContentAddressMethod::RecursiveFileIngestion => CaMethod::Recursive,
        };
        let hash = ca.get_hash()?;

        Ok(Some(ContentAddress {
            method,
            algo: match HashType::from(hash.get_hash_type()?) {
                HashType::Md5 => "md5",
                HashType::Sha1 => "sha1",
                HashType::Sha256 => "sha256",
                HashType::Sha512 => "sha512",
            }
            .to_string(),
            hash: hash.get_hash()?.to_vec(),
        }))
    }
}

pub trait ValidPathInfoBuilderExt {
    fn write_path_info(&mut self, info: &PathInfo, store_dir: &str);
}

impl ValidPathInfoBuilderExt for legacy_protocol::valid_path_info::Builder<'_> {
    fn write_path_info(&mut self, info: &PathInfo, store_dir: &str) {
        self.reborrow()
            .init_path()
            .set_raw(info.path.to_full(store_dir).as_bytes());

        let mut unkeyed = self.reborrow().init_unkeyed_valid_path_info();
        match &info.deriver {
            Some(deriver) => unkeyed
                .reborrow()
                .init_deriver()
                .init_some()
                .set_raw(deriver.to_full(store_dir).as_bytes()),
            None => unkeyed.reborrow().init_deriver().set_none(()),
        }

        {
            let mut hash = unkeyed.reborrow().init_nar_hash();
            hash.set_hash(&info.nar_hash.bytes);
            hash.set_hash_type(info.nar_hash.hash_type.into());
        }

        unkeyed.set_nar_size(info.nar_size);
        unkeyed.set_registration_time(info.registration_time);
        unkeyed.set_ultimate(info.ultimate);

        unkeyed
            .reborrow()
            .init_references(info.references.len() as u32)
            .write_store_paths(&info.references, store_dir);

        let mut sigs = unkeyed.reborrow().init_sigs(info.sigs.len() as u32);
        for (i, sig) in info.sigs.iter().enumerate() {
            sigs.set(i as u32, sig.as_bytes());
        }

        // `ca` is left as the default `none`: nothing here is content-addressed yet.
    }
}

/// The client's log stream — a capnp RPC client capability, i.e. the "remote"
/// object these methods actually operate on.
pub trait LogStreamExt {
    /// Open a build activity on the client.
    ///
    /// `actBuild` has a required field layout the client indexes into blindly
    /// (`lix/libmain/progress-bar.cc:159-174`): field 0 is the derivation
    /// path, field 1 the machine name, and fields 2 and 3 are integers that
    /// must both be `1` or the client throws "log message indicated repeating
    /// builds". Sending the wrong shape crashes the client rather than
    /// degrading, so these four fields are mandatory.
    async fn start_activity(&self, id: u64, drv_path: &str) -> Result<(), capnp::Error>;
    async fn push_log_line(&self, activity_id: u64, line: &[u8]) -> Result<(), capnp::Error>;
    async fn stop_activity(&self, id: u64) -> Result<(), capnp::Error>;
}

impl LogStreamExt for log_stream::Client {
    async fn start_activity(&self, id: u64, drv_path: &str) -> Result<(), capnp::Error> {
        let mut request = self.push_request();
        {
            let mut event = request.get().init_e();
            let mut start = event.reborrow().init_start_activity();
            start.set_level(crate::types_capnp::Verbosity::Info);
            start.set_id(id);
            start.set_type(crate::logging_capnp::ActivityType::Build);
            start.set_text(format!("building {drv_path}").as_bytes());
            start.set_parent(0);

            let mut fields = start.init_fields(4);
            fields.reborrow().get(0).set_s(drv_path.as_bytes());
            fields.reborrow().get(1).set_s(b"kubernix");
            fields.reborrow().get(2).set_i(1);
            fields.reborrow().get(3).set_i(1);
        }
        request.send().await?;
        Ok(())
    }

    async fn push_log_line(&self, activity_id: u64, line: &[u8]) -> Result<(), capnp::Error> {
        let mut request = self.push_request();
        {
            let mut event = request.get().init_e();
            let mut result = event.reborrow().init_result();
            result.set_id(activity_id);
            result.set_type(crate::logging_capnp::ResultType::BuildLogLine);
            let mut fields = result.init_fields(1);
            fields.reborrow().get(0).set_s(line);
        }
        request.send().await?;
        Ok(())
    }

    async fn stop_activity(&self, id: u64) -> Result<(), capnp::Error> {
        let mut request = self.push_request();
        request.get().init_e().init_stop_activity().set_id(id);
        request.send().await?;
        self.synchronize_request().send().promise.await?;
        Ok(())
    }
}

impl JobQueue {
    /// Submit a job, relay its log into the client's `LogStream`, and return
    /// the outcome.
    ///
    /// The log subscription and result consumer are created *before* the job
    /// is submitted: logs are core NATS with no replay, so subscribing
    /// afterwards races the worker and can drop the opening lines.
    ///
    /// This future is deliberately `!Send` — it holds capnp capabilities —
    /// which is why it runs on the connection's `LocalSet`. The NATS futures
    /// it awaits are `Send`, and awaiting a `Send` future from a `!Send` task
    /// is fine.
    pub(crate) async fn dispatch(
        &self,
        job: crate::jobs::BuildJob,
        logger: &log_stream::Client,
    ) -> eyre::Result<crate::jobs::JobOutcome> {
        use eyre::WrapErr as _;

        let job_id = job.job_id;

        let mut logs = self
            .subscribe_logs(&job_id)
            .await
            .wrap_err("subscribing to the job's logs")?;
        let consumer = self
            .result_consumer(&job_id)
            .await
            .wrap_err("creating a result consumer")?;

        self.submit(&job).await.wrap_err("submitting the job")?;

        // The client sees a build activity for the job, and each log line
        // arrives as a result on it — the same shape a local build produces,
        // so it renders identically.
        let activity_id = job_id.as_u128() as u64;
        logger
            .start_activity(activity_id, job.derivation_path.as_str())
            .await?;

        let outcome = {
            let mut outcome_fut = Box::pin(self.await_outcome(consumer));
            loop {
                tokio::select! {
                    // Bias toward draining logs so the tail is not lost when the
                    // outcome and the final lines arrive together.
                    biased;
                    Some(message) = logs.next() => {
                        logger.push_log_line(activity_id, &message.payload).await?;
                    }
                    outcome = &mut outcome_fut => break outcome?,
                }
            }
        };

        // Drain whatever is already buffered before closing the activity.
        while let Ok(Some(message)) =
            tokio::time::timeout(std::time::Duration::from_millis(50), logs.next()).await
        {
            logger.push_log_line(activity_id, &message.payload).await?;
        }

        logger.stop_activity(activity_id).await?;
        Ok(outcome)
    }
}
